package com.tracy.werewolf.service;
import com.tracy.werewolf.dto.CreateRoomRequest; import com.tracy.werewolf.model.*; import org.springframework.stereotype.Service; import java.util.*;
@Service
public class GameRoomService {
 private final Map<String, GameRoom> rooms = new HashMap<>(); private final Random random = new Random(); private final BoardService boardService;
 public GameRoomService(BoardService boardService){this.boardService=boardService;}
 public GameRoom createRoom(CreateRoomRequest request){
  int pc=request.getPlayerCount(); if(pc<9||pc>16) throw new IllegalArgumentException("Player count must be between 9 and 16");
  if(request.getHostName()==null||request.getHostName().trim().isEmpty()) throw new IllegalArgumentException("Host name is required");
  GameRoom room=new GameRoom(); room.setRoomCode(generateUniqueRoomCode()); room.setPlayerCount(pc); room.setPhase(GamePhase.WAITING); room.setRound(0);
  if(request.isCustomMode()) { validateCustomRoles(request.getCustomRoles(), pc); room.setCustomMode(true); room.setCustomRoles(cleanRoles(request.getCustomRoles())); }
  else { Board board=boardService.getBoard(request.getBoardId()); if(board.getPlayerCount()!=pc) throw new IllegalArgumentException("Board does not match player count"); room.setBoardId(board.getId()); room.setCustomMode(false); }
  String hostId=UUID.randomUUID().toString(); Player host=new Player(hostId, request.getHostName().trim(), 1, true); room.setHostPlayerId(hostId); room.getPlayers().add(host); rooms.put(room.getRoomCode(), room); return room;
 }
 public GameRoom joinRoom(String roomCode,String playerName){ GameRoom room=getRoom(roomCode); if(room.getPhase()!=GamePhase.WAITING) throw new IllegalStateException("Game already started"); if(room.getPlayers().size()>=room.getPlayerCount()) throw new IllegalStateException("Room is full"); if(playerName==null||playerName.trim().isEmpty()) throw new IllegalArgumentException("Player name is required"); room.getPlayers().add(new Player(UUID.randomUUID().toString(), playerName.trim(), room.getPlayers().size()+1, false)); return room; }
 public GameRoom fillBots(String roomCode){ GameRoom room=getRoom(roomCode); if(room.getPhase()!=GamePhase.WAITING) throw new IllegalStateException("Game already started"); while(room.getPlayers().size()<room.getPlayerCount()) room.getPlayers().add(new Player(UUID.randomUUID().toString(), "Bot " + (room.getPlayers().size()+1), room.getPlayers().size()+1, false)); return room; }
 public GameRoom startGame(String roomCode,String playerId){ GameRoom room=getRoom(roomCode); requireHost(room,playerId,"Only host can start the game"); if(room.getPhase()!=GamePhase.WAITING) throw new IllegalStateException("Game already started"); if(room.getPlayers().size()!=room.getPlayerCount()) throw new IllegalStateException("Room is not full yet"); assignRoles(room); room.setPhase(GamePhase.NIGHT); room.setRound(1); return room; }
 public GameRoom nextPhase(String roomCode,String playerId){ GameRoom room=getRoom(roomCode); requireHost(room,playerId,"Only host can control game phase"); switch(room.getPhase()){ case WAITING -> throw new IllegalStateException("Game has not started"); case NIGHT -> room.setPhase(GamePhase.DAY_DISCUSSION); case DAY_DISCUSSION -> room.setPhase(GamePhase.VOTING); case VOTING -> { if(isGameOver(room)) room.setPhase(GamePhase.FINISHED); else {room.setPhase(GamePhase.NIGHT); room.setRound(room.getRound()+1);} } case FINISHED -> throw new IllegalStateException("Game already finished"); } return room; }
 public GameRoom getRoom(String roomCode){ GameRoom room=rooms.get(roomCode); if(room==null) throw new IllegalArgumentException("Room not found"); return room; }
 public Role getPlayerRole(String roomCode,String playerId){ return getRoom(roomCode).getPlayers().stream().filter(p->p.getId().equals(playerId)).findFirst().orElseThrow(()->new IllegalArgumentException("Player not found")).getRole(); }
 private void assignRoles(GameRoom room){ List<Role> pool=buildRolePool(room); Collections.shuffle(pool); for(int i=0;i<room.getPlayers().size();i++) room.getPlayers().get(i).setRole(pool.get(i)); }
 private List<Role> buildRolePool(GameRoom room){ Map<Role,Integer> map = room.isCustomMode()? room.getCustomRoles() : boardService.getBoard(room.getBoardId()).getRoles(); List<Role> pool=new ArrayList<>(); map.forEach((r,c)->{ for(int i=0;i<c;i++) pool.add(r); }); return pool; }
 private void validateCustomRoles(Map<Role,Integer> roles,int playerCount){ if(roles==null||roles.isEmpty()) throw new IllegalArgumentException("Custom roles are required"); int total=roles.values().stream().filter(Objects::nonNull).mapToInt(Integer::intValue).sum(); if(total!=playerCount) throw new IllegalArgumentException("Role total must equal player count"); int wolves=roles.entrySet().stream().filter(e->isWolfRole(e.getKey())).mapToInt(e->e.getValue()==null?0:e.getValue()).sum(); if(wolves<3) throw new IllegalArgumentException("At least 3 wolf team roles are required"); if(wolves>=playerCount/2.0) throw new IllegalArgumentException("Wolf team roles should be less than half of players"); if(roles.getOrDefault(Role.VILLAGER,0)<1) throw new IllegalArgumentException("At least 1 villager is recommended"); }
 private Map<Role,Integer> cleanRoles(Map<Role,Integer> roles){ Map<Role,Integer> out=new LinkedHashMap<>(); roles.forEach((r,c)->{ if(c!=null&&c>0) out.put(r,c); }); return out; }
 private boolean isWolfRole(Role r){ return switch(r){ case WEREWOLF,WOLF_KING,WHITE_WOLF_KING,BEAUTY_WOLF,GARGOYLE,MECHANICAL_WOLF,HIDDEN_WOLF,DEMON_KNIGHT,SNOW_WOLF,THICK_SKIN_WOLF -> true; default -> false;}; }
 private boolean isGameOver(GameRoom room){ long wolves=room.getPlayers().stream().filter(Player::isAlive).filter(p->isWolfRole(p.getRole())).count(); long others=room.getPlayers().stream().filter(Player::isAlive).filter(p->!isWolfRole(p.getRole())).count(); return wolves==0||wolves>=others; }
 private void requireHost(GameRoom room,String playerId,String msg){ if(!Objects.equals(room.getHostPlayerId(), playerId)) throw new IllegalStateException(msg); }
 private String generateUniqueRoomCode(){ String code; do{ code=String.valueOf(100000+random.nextInt(900000)); }while(rooms.containsKey(code)); return code; }
}
