package com.tracy.werewolf.model;
public enum Role {
    WEREWOLF, WOLF_KING, WHITE_WOLF_KING, BEAUTY_WOLF, GARGOYLE, MECHANICAL_WOLF, HIDDEN_WOLF, DEMON_KNIGHT, SNOW_WOLF, THICK_SKIN_WOLF,
    VILLAGER,
    SEER, WITCH, HUNTER, GUARD, IDIOT, KNIGHT, GRAVE_KEEPER, MAGICIAN, DREAM_CATCHER, BEAR_TRAINER, FOX, PSYCHIC, EXORCIST, LITTLE_GIRL, BOMB_EXPERT, ALCHEMIST, PRIEST, MOON_PRIEST, AWAKENED_HUNTER, AWAKENED_SEER, AWAKENED_WITCH,
    CUPID, THIEF, WILD_CHILD, MIXED_BLOOD, LOVERS, SHADOW, PIPER
}
